// INGEN TULLER MED MODELLEN UTEN Å SI FRA !!! :)

const model = {
    app: {
        currentPage: 'addPlaces',
        currentUser: null,
        selectedPlace: 0,
        isAdmin: false,

        page: [
            'loginPage',
            'mainFeed',
            'addPlaces',
            'placePage',
            'registerUser',
        ]
    },

    viewState: {
        registerUser: {
            username: '',
            email: '',
            password: '',
            repeatPassword: '',
        },

        mainFeed: {
            search: '',
        },

        login: {
            userName: '',
            password: '',
            anonymous: false,
        },

        addPlace: {
            id: null,
            userID: null,
            title: '',
            address: '',
            city: '',
            categoryID: [],
            image: '',
            rateCoffee: null,
            rateFood: null,
            description: '',
        },
    },

    data: {
        users: [
            {
                id: 0,
                userName: 'Anita',
                email: 'anita@getacademy.no',
                password: 'Bjarne007',
                placesAdded: [0, 1],
                isAdmin: true,
            },
            {
                id: 1,
                userName: 'Spooky',
                email: 'test@email.com',
                password: '',
                placesAdded: [1],
                isAdmin: false,
            },
            {
                id: 2,
                userName: 'Glutenfrielskeren73',
                email: 'hatergluten@gmail.com',
                password: 'GlutenErEkkelt66',
                placesAdded: [0],
                isAdmin: false,
            },
            {
                id: 3,
                userName: 'Spicymama',
                email: 'spicy@outlook.com',
                password: 'passord123',
                placesAdded: [0],
                isAdmin: false,
            },
            {
                id: 4,
                userName: 'McLovin',
                email: 'mclovin@superbad.com',
                password: 'MohammedIsTheMostCommonlyUsedNameOnEarth',
                placesAdded: [0],
                isAdmin: false,
            },
            {
                id: 5,
                userName: 'I_Hate_Gluten',
                email: 'olanordmann@hotmail.com',
                password: 'glutenerdjevelensverk112',
                placesAdded: [0],
                isAdmin: false,
            },
            {
                id: 6,
                userName: 'CoffeAndGlutenLover67',
                email: 'Kaffe@gmail.com',
                password: 'kaffinamnam185',
                placesAdded: [0],
                isAdmin: false,
            },
        ],

        category: [
            {
                id: 0, name: 'cafe',
            },
            {
                id: 1, name: 'bakeri',
            },
            {
                id: 2, name: 'restaurant',
            },
        ],

        placesList: [
            {
                id: 0,
                userID: 0,
                title: 'GLH Glutenfrihuset Tøyen',
                address: 'Ålebergveien 50A',
                city: 'Oslo',
                categoryID: [0, 1],
                image: 'media/glh.jpg',
                rateCoffee: 5,
                rateFood: 5,
                description: 'Velkommen til GLH Glutenfrihuset - ditt glutenfrie bakeri i OSlo',
            },
            {
                id: 1,
                userID: 0,
                title: 'En restaurant',
                address: 'En adresse - Veien10B',
                city: 'Bergen',
                categoryID: [2, 0],
                image: 'media/bergen.jpg',
                rateCoffee: 2,
                rateFood: 4,
                description: 'SKIKKELIG dårlig kaffe, men ok bra mat',
            },
            {
                id: 2,
                userID: 0,
                title: 'Cupcakehuset Jåblom Bakst',
                address: 'Haraldsgata 191',
                city: 'Haugesund',
                categoryID: [2, 0],
                image: 'media/cupcake.png',
                rateCoffee: 2,
                rateFood: 5,
                description: 'Knall gode muffins av alle slag',
            },
            {
                id: 3,
                userID: 0,
                title: 'McDonalds',
                address: 'Storgata 15',
                city: 'Oslo',
                categoryID: [2, 0],
                image: 'media/mcdonalds.jpg',
                rateCoffee: 3,
                rateFood: 4,
                description: 'Grei kaffe og mat. Fikk litt vondt i magen. Bråkete plass.',
            },
            {
                id: 4,
                userID: 0,
                title: 'Godt Brød',
                address: 'Thorvald Meyers gate 49',
                city: 'Oslo',
                categoryID: [0, 1],
                image: 'media/godtbrod.jpg',
                rateCoffee: 4,
                rateFood: 2,
                description: 'De tilbyr kun sandwich og brød uten gluten. Hadde gledet meg til kafè-tur med minstesønnen. Ble et kjedelig besøk. OK kaffe da :)',
            },
            {
                id: 5,
                userID: 0,
                title: 'Cafe Avec',
                address: 'Rådhusgata 4',
                city: 'Storsteinnes',
                categoryID: [0, 1],
                image: 'media/cafeavec.jpg',
                rateCoffee: 4,
                rateFood: 3,
                description: 'Spiste en glutenfri pizza, bunnen var ikke ordentlig stekt!! Ble litt dårlig. Men veldig god iskaffe!',
            },
            {
                id: 6,
                userID: 0,
                title: 'Pinocchio Mat og Vinbar',
                address: 'Strandgaten 73',
                city: 'Bergen',
                categoryID: [2],
                image: 'media/pinocchiomatogvinbar.jpg',
                rateCoffee: 2,
                rateFood: 5,
                description: 'Nyyyyydelig tapas. Det var så mye å velge mellom at jeg ikke savnet glutenfritt brød. Jæskla god rødvin i tillegg. Tok en kaffe til dessert, den var også god.',
            },
            {
                id: 7,
                userID: 0,
                title: 'CRAVING',
                address: 'Strandgaten 78',
                city: 'Bergen',
                categoryID: [0],
                image: 'media/craving.jpg',
                rateCoffee: 4,
                rateFood: 5,
                description: 'Spiste en beligsk vaffel og en smoothiebowl - dritgod!! Anbefales virkelig!!!',
            },
            {
                id: 8,
                userID: 0,
                title: 'Joe & the Juice',
                address: 'Karl Johans gate 25',
                city: 'Oslo',
                categoryID: [0],
                image: 'media/joeandthejuice.jpg',
                rateCoffee: 2,
                rateFood: 3,
                description: 'Han i kassa prøvde seg på meg(???). Litt ubehagelig. Vanvittig godt glutenfritt brød da, så kommer nok til å dra tilbake.',
            },
            {
                id: 9,
                userID: 0,
                title: 'Egon',
                address: 'Smedasundet 93',
                city: 'Haugesund',
                categoryID: [2],
                image: 'media/egon.jpg',
                rateCoffee: 3,
                rateFood: 3,
                description: 'Det tok litt tid før maten kom. Men da den kom var den god. Grei kaffe, men kommer ikke til å dra tilbake for den as.',
            },
        ],
    },
}

